version: "3.8"

services:
  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - aerospike-data:/opt/aerospike/data
    restart: unless-stopped

volumes:
  aerospike-data:
